# Generated by Django 4.0.6 on 2022-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_datecreation_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(default='History', through='news.PostCategory', to='news.category'),
        ),
    ]
